### ISSUE TITLE
App Crashing Null pointer exception

### ISSUE THREAD

**Issue by sabyasachiRepo** [ibm-cloud-security/appid-clientsdk-android#136]
App crashing while logging in. 

Fatal Exception: java.lang.RuntimeException
Unable to start activity ]com.ibm.cloud.appid.android.internal.authorizationmanager.ChromeTabActivity}: java.lang.NullPointerException

Galaxy S5
Android: 4.4.2

**Comment by motyd** [comment]
Can you provide the following:
- SDK Version
- Usage code + how to reproduce
- Stack Trace

Does this happen always? Only in certain circumstances?

**Comment by sabyasachiRepo** [comment]
SDK version:4.0.2

Get to know this issue from firebase crashlytics report. Not sure about origin. 

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'com.ibm.cloud.appid.android.internal.OAuthManager com.ibm.cloud.appid.android.internal.authorizationmanager.AuthorizationFlowContext.getOAuthManager()' on a null object reference
       at com.ibm.cloud.appid.android.internal.authorizationmanager.ChromeTabActivity.onCreate(ChromeTabActivity.java:61)
       at android.app.Activity.performCreate(Activity.java:6550)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1120)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3077)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3233)
       at android.app.ActivityThread.access$1000(ActivityThread.java:197)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6873)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

    It does not happen frequently as per crash report.  But it does happen.

**Comment by motyd** [comment]
Closing this as it looks like a similar issue to #137.
No need to maintain two issues if the root cause is probably the same.
