### ISSUE TITLE
Incompatibility between App ID android SDK 1.1.2 and MobilePush 3.6.4

### ISSUE THREAD

**Issue by l2fprod** [ibm-cloud-security/appid-clientsdk-android#54]
With the following libraries in my project

```
    compile 'com.github.ibm-cloud-security:appid-clientsdk-android:1.+'
    compile 'com.google.code.gson:gson:2.7'
    compile 'com.github.vlonjatg:progress-activity:v2.0.3'

    compile group: 'com.ibm.mobilefirstplatform.clientsdk.android',
            name: 'push',
            version: '3+',
            ext: 'aar',
            transitive: true
```

the App ID login widget fails with

```
11-16 11:34:00.947 20790-20790/serverlessfollowup.app E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: serverlessfollowup.app, PID: 20790
                                                                        java.lang.NoClassDefFoundError: Failed resolution of: Lcom/squareup/okhttp/OkHttpClient;
                                                                            at com.ibm.bluemix.appid.android.internal.network.AppIDRequest.<clinit>(AppIDRequest.java:32)
                                                                            at com.ibm.bluemix.appid.android.internal.tokenmanager.TokenManager.createAppIDRequest(TokenManager.java:85)
                                                                            at com.ibm.bluemix.appid.android.internal.tokenmanager.TokenManager.retrieveTokens(TokenManager.java:92)
                                                                            at com.ibm.bluemix.appid.android.internal.tokenmanager.TokenManager.obtainTokens(TokenManager.java:80)
                                                                            at com.ibm.bluemix.appid.android.internal.authorizationmanager.ChromeTabActivity.onBroadcastReceived(ChromeTabActivity.java:109)
                                                                            at com.ibm.bluemix.appid.android.internal.authorizationmanager.ChromeTabActivity.access$000(ChromeTabActivity.java:34)
                                                                            at com.ibm.bluemix.appid.android.internal.authorizationmanager.ChromeTabActivity$1.onReceive(ChromeTabActivity.java:78)
                                                                            at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
                                                                            at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
                                                                            at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                            at android.os.Looper.loop(Looper.java:164)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                         Caused by: java.lang.ClassNotFoundException: Didn't find class "com.squareup.okhttp.OkHttpClient" on path: DexPathList[[zip file "/data/app/serverlessfollowup.app-jT93dcdJcqRTkhuhOLYv5w==/base.apk", zip file "/data/app/serverlessfollowup.app-jT93dcdJcqRTkhuhOLYv5w==/split_lib_dependencies_apk.apk", zip file "/data/app/serverlessfollowup.app-jT93dcdJcqRTkhuhOLYv5w==/split_lib_slice_0_apk.apk", zip file "/data/app/serverlessfollowup.app-jT93dcdJcqRTkhuhOLYv5w==/split_lib_slice_1_apk.apk", zip file "/data/app/serverlessfollowup.app-jT93dcdJcqRTkhuhOLYv5w==/split_lib_slice_2_apk.apk", zip file "/data/app/serverlessfollowup.app-jT93dcdJcqRTkhuhOLYv5w==/split_lib_slice_3_apk.apk", zip file "/data/app/serverlessfollowup.app-jT93dcdJcqRTkhuhOLYv5w==/split_lib_slice_4_apk.apk", zip file "/data/app/serverlessfollowup.app-jT93dcdJcqRTkhuhOLYv5w==/split_lib_slice_5_apk.apk", zip file "/data/app/serverlessfollowup.app-jT93dcdJcqRTkhuhOLYv5w==/split_lib_slice_6_apk.apk", zip file "/data/app/serverlessfollowup.app-jT93dcdJcqRTkhuhOLYv5w==/split_lib_slice_7_apk.apk", zip file "/data/app/serverlessfollowup.app-jT93dcdJcqRTkhuhOLYv5w==/split_lib_slice_8_apk.apk", zip file "/data/app/serverlessfollowup.app-jT93dcdJcqRTkhuhOLYv5w==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/serverlessfollowup.app-jT93dcdJcqRTkhuhOLYv5w==/lib/x86, /system/lib, /vendor/lib]]
                                                                            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                            at com.ibm.bluemix.appid.android.internal.network.AppIDRequest.<clinit>(AppIDRequest.java:32) 
                                                                            at com.ibm.bluemix.appid.android.internal.tokenmanager.TokenManager.createAppIDRequest(TokenManager.java:85) 
                                                                            at com.ibm.bluemix.appid.android.internal.tokenmanager.TokenManager.retrieveTokens(TokenManager.java:92) 
                                                                            at com.ibm.bluemix.appid.android.internal.tokenmanager.TokenManager.obtainTokens(TokenManager.java:80) 
                                                                            at com.ibm.bluemix.appid.android.internal.authorizationmanager.ChromeTabActivity.onBroadcastReceived(ChromeTabActivity.java:109) 
                                                                            at com.ibm.bluemix.appid.android.internal.authorizationmanager.ChromeTabActivity.access$000(ChromeTabActivity.java:34) 
                                                                            at com.ibm.bluemix.appid.android.internal.authorizationmanager.ChromeTabActivity$1.onReceive(ChromeTabActivity.java:78) 
                                                                            at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297) 
                                                                            at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46) 
                                                                            at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                            at android.os.Looper.loop(Looper.java:164) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
```

The issue seems to come from this change in the push module:
https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-android-push/commit/8eeba7f8c5e13262ed08ffa1a77958e30da234c5

which update the android core to com.ibm.mobilefirstplatform.clientsdk.android:core:3.1.3

and in this version the OkHttp library is no longer prefixed by the group name.

If I set the mobile push version to 3.6.3 then it works as expected.

A similar issue https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-android-core/issues/50

**Comment by motyd** [comment]
Closing this as it relates to old versions of App ID and other SDKs. 

As far as we know, the new App ID SDKs should be compatible.
